export const FLASHCARDS = [
  { en: 'Footwork', zh: '腳部練習' },
  { en: 'Second Position', zh: '第二種姿勢' },
  { en: 'Single Leg', zh: '單腿練習' },
  { en: 'Hundred', zh: '百次拍擊' },
  { en: 'Bend & Stretch', zh: '屈伸練習' },
  { en: 'Lift & Lower', zh: '抬腿與放腿' },
  { en: 'Adductor Stretch', zh: '伸展內收肌' },
  { en: 'Short Spine Prep', zh: '脊椎捲曲準備動作' },
  { en: 'Short Spine', zh: '脊椎捲曲' },
  { en: 'Midback Series', zh: '中背部系列動作' },
  { en: 'Back Rowing Preps', zh: '後划準備動作' },
  { en: 'Side Arm Preps Sitting', zh: '側坐手臂準備動作' },
  { en: 'Side Twist Sitting', zh: '側轉坐姿' },
  { en: 'Front Rowing Preps', zh: '前划準備動作' },
  { en: 'Stomach Massage', zh: '腹部按摩' },
  { en: 'Arms Pulling Straps (Long Box)', zh: '雙臂拉動拉環（盒子豎放）' },
  { en: 'Round Back (Short Box)', zh: '弓背（盒子橫放）' },
  { en: 'Straight Back (Short Box)', zh: '直背（盒子橫放）' },
  { en: 'Twist (Short Box)', zh: '扭轉（盒子橫放）' },
  { en: 'Tree (Short Box)', zh: '樹姿（盒子橫放）' },
  { en: 'Elephant', zh: '大象姿' },
  { en: 'Mermaid', zh: '美人魚姿' },
  { en: 'Leg Circles', zh: '雙腿畫弧' },
  { en: 'Knee Stretches', zh: '膝部伸展' },
  { en: 'Running', zh: '跑步運動' },
  { en: 'Hip Lift', zh: '髖部上抬' },
  { en: 'Hip Rolls', zh: '髖部起伏' },
  { en: 'Single Thigh Stretch', zh: '單側大腿伸展' },
  { en: 'Side Splits', zh: '側劈叉' },
  { en: 'Front Splits', zh: '前劈叉' },
  { en: 'Back Splits', zh: '後劈叉' },
  { en: 'Coordination', zh: '協調性' },
  { en: 'Backstroke Prep', zh: '仰泳練習準備動作' },
  { en: 'Long Stretch', zh: '直線伸展' },
  { en: 'Down Stretch', zh: '向下伸展' },
  { en: 'Up Stretch', zh: '向上伸展' },
  { en: 'Chest Expansion', zh: '胸部擴張' },
  { en: 'Star Prep', zh: '星姿準備動作' },
];
